name: Build

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:    
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Build
        run: |
          npm install
          npx webpack

      - name: Electron Forge Action
        # You may pin to the exact commit or the version.
        # uses: yinxulai/actions-electron-forge@456a6517c5241e4d693507b99a30dac8fe622102
        uses: yinxulai/actions-electron-forge@0.05
        with:
          # GitHub authentication token
          github_token: ${{ secret.GITHUB_TOKEN }}
          # Whether the app should be released after a successful build
          release: true

  release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
     
      - name: Get latest release
        uses: rez0n/actions-github-release@main
        id: node_release
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "OOT-Multiworld-Tracker/Multiworld-Tracker"
          type: "latest"
        
      - name: Sentry Release
        uses: getsentry/action-release@v1.1.6
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: development
          version: ${{ steps.node_release.outputs.release }}
